### ISSUE TITLE
instrallation issue

### ISSUE THREAD

**Issue by magnusrattray** [sods/ods#11]
The SageMath team had an issue installing through pip install --user --dev pods

Installing collected packages: pods
  Running setup.py install for pods
    /projects/22c1772e-0ee1-418a-bb3d-26d649985c08/.local/lib/python3.4/site-packages/setuptools/dist.py:364: UserWarning: Normalizing 'v0.0.2-alpha' to '0.0.2a0'
      normalized_version,
      File "/projects/22c1772e-0ee1-418a-bb3d-26d649985c08/.local/lib/python3.4/site-packages/pods/test.py", line 3
        def test_datasets:
                         ^
    SyntaxError: invalid syntax

but the package does end up in .local so we still managed to use it.

**Comment by magnusrattray** [comment]
There was a typo above, the command was 

pip3 install --user --pre pods

but the error message is correct

**Comment by lawrennd** [comment]
Thanks Magnus, @zhenwend, could you take a quick look at this?
