### ISSUE TITLE
ods is not installable via pip

### ISSUE THREAD

**Issue by jameshensman** [sods/ods#5]
This is release-blocking GPy, https://github.com/SheffieldML/GPy/issues/163

I think the fix is to register on Pypi as non-prerelease software.

Max: There are missing entries in the default config, which makes importing error.

**Comment by lawrennd** [comment]
It should be installable. I think you just need the prerelease flag on some
systems. @mikecroucher and @mzwiessele are putting together the priorities
for next release. Examples should probably be reviewed alongside tests and
and benchmarks.

**Comment by jameshensman** [comment]
@mzwiessele, could you detail the problems you described with this so @lawrennd can fix, please?

**Comment by jameshensman** [comment]
@mzwiessele reports this fixed.
