### ISSUE TITLE
Downloading olympic_100m_men dataset floods stdout

### ISSUE THREAD

**Issue by markvdw** [sods/ods#8]
I noticed an issue when downloading the olympic_100m_men() dataset (originally using GPy). On a fresh pip install of pods, the terminal is flooded with ==== symbols, presumably from a status indicator of the download. Downloading proceeds incredibly slowly, so I reverted to manually downloading the data and placing it in the ods_data_cache folder. This issue does hinder ease of use though, as it stopped me from being able to download the data through the code interface.

Mark

**Comment by lawrennd** [comment]
Hi Mark,

Are you in Python3?

I upgraded it to python3 recently but it may have broke python2 ... I
haven't got full test coverage on the software download ...

**Comment by markvdw** [comment]
I am still on Python 2, so that could make sense. Upgrading's priority is below "finishing thesis"...

**Comment by lawrennd** [comment]
Yes sorry Mark, try an older version if you don't have time to investigate
the fix!

**Comment by markvdw** [comment]
A quick-fix solution would be to run the download functions from a python3 shell, and then continuing as normal from python2, with the cached downloads, but if I find the fix, I'll post about it.

**Comment by lawrennd** [comment]
Thanks Mark!
